# Generated by Django 2.2.3 on 2019-07-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountid', models.AutoField(db_column='AccountID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('firstname', models.CharField(db_column='FirstName', max_length=255)),
                ('lastname', models.CharField(db_column='LastName', max_length=255)),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('phone', models.CharField(db_column='Phone', max_length=11, unique=True)),
                ('profilepicture', models.CharField(blank=True, db_column='ProfilePicture', max_length=255, null=True)),
                ('valid', models.IntegerField(blank=True, db_column='Valid', null=True)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('lastmodified', models.DateTimeField(blank=True, db_column='LastModified', null=True)),
            ],
            options={
                'db_table': 'Account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accounttype',
            fields=[
                ('accounttypeid', models.AutoField(db_column='AccountTypeID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255, unique=True)),
                ('readerright', models.IntegerField(blank=True, db_column='ReaderRight', null=True)),
                ('journalistright', models.IntegerField(blank=True, db_column='JournalistRight', null=True)),
                ('adminright', models.IntegerField(blank=True, db_column='AdminRight', null=True)),
                ('accountmng', models.IntegerField(blank=True, db_column='AccountMng', null=True)),
                ('accounttypemng', models.IntegerField(blank=True, db_column='AccountTypeMng', null=True)),
                ('articlemng', models.IntegerField(blank=True, db_column='ArticleMng', null=True)),
                ('commentmng', models.IntegerField(blank=True, db_column='CommentMng', null=True)),
                ('bookmarkmng', models.IntegerField(blank=True, db_column='BookmarkMng', null=True)),
                ('feedbackmng', models.IntegerField(blank=True, db_column='FeedbackMng', null=True)),
                ('imagemng', models.IntegerField(blank=True, db_column='ImageMng', null=True)),
            ],
            options={
                'db_table': 'AccountType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleid', models.AutoField(db_column='ArticleID', primary_key=True, serialize=False)),
                ('heading', models.CharField(db_column='Heading', max_length=255)),
                ('shortdescription', models.TextField(blank=True, db_column='ShortDescription', null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('categoryid', models.IntegerField(db_column='CategoryID')),
                ('subcategoryid', models.IntegerField(blank=True, db_column='SubCategoryID', null=True)),
                ('censored', models.IntegerField(blank=True, db_column='Censored', null=True)),
                ('draft', models.IntegerField(blank=True, db_column='Draft', null=True)),
                ('trash', models.IntegerField(blank=True, db_column='Trash', null=True)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('lastmodified', models.DateTimeField(blank=True, db_column='LastModified', null=True)),
            ],
            options={
                'db_table': 'Article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmarkid', models.AutoField(db_column='BookmarkID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
            ],
            options={
                'db_table': 'Bookmark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(db_column='CommentID', primary_key=True, serialize=False)),
                ('repliedcommentid', models.IntegerField(blank=True, db_column='RepliedCommentID', null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('nooflikes', models.IntegerField(blank=True, db_column='NoOfLikes', null=True)),
                ('level', models.IntegerField(db_column='Level')),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
            ],
            options={
                'db_table': 'Comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageid', models.AutoField(db_column='ImageID', primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, db_column='Source', max_length=255, null=True)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('thumbnail', models.IntegerField(blank=True, db_column='Thumbnail', null=True)),
            ],
            options={
                'db_table': 'Image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageid', models.AutoField(db_column='MessageID', primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
            ],
            options={
                'db_table': 'Message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Updatearticleactivity',
            fields=[
                ('actionid', models.AutoField(db_column='ActionID', primary_key=True, serialize=False)),
                ('censored', models.IntegerField(blank=True, db_column='Censored', null=True)),
                ('draft', models.IntegerField(blank=True, db_column='Draft', null=True)),
                ('trash', models.IntegerField(blank=True, db_column='Trash', null=True)),
                ('created', models.IntegerField(blank=True, db_column='Created', null=True)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
            ],
            options={
                'db_table': 'UpdateArticleActivity',
                'managed': False,
            },
        ),
    ]
